# Generated by Django 3.2.11 on 2025-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='职位名称')),
                ('company', models.CharField(max_length=200, verbose_name='公司名称')),
                ('job_type', models.IntegerField(choices=[(0, '全职'), (1, '兼职'), (2, '实习'), (3, '外包')], default=0, verbose_name='职位类型')),
                ('salary_min', models.IntegerField(default=0, verbose_name='最低薪资(K)')),
                ('salary_max', models.IntegerField(default=0, verbose_name='最高薪资(K)')),
                ('experience', models.IntegerField(choices=[(0, '不限'), (1, '1年以下'), (2, '1-3年'), (3, '3-5年'), (4, '5-10年'), (5, '10年以上')], default=0, verbose_name='经验要求')),
                ('education', models.IntegerField(choices=[(0, '不限'), (1, '初中及以下'), (2, '高中/中专'), (3, '大专'), (4, '本科'), (5, '硕士'), (6, '博士')], default=0, verbose_name='学历要求')),
                ('description', models.TextField(blank=True, null=True, verbose_name='职位描述')),
                ('location', models.CharField(max_length=100, verbose_name='工作地点')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('pv', models.IntegerField(default=0, verbose_name='浏览量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('expire', models.IntegerField(default=7, verbose_name='有效期(天)')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '招聘岗位',
                'db_table': 'job_position',
                'ordering': ['-timestamp'],
            },
        ),
    ]
